import type { Translations } from './types';

export const translations: Translations = {
    en: {
        headerTitle: 'Life After People',
        navYear: 'First Year',
        navCentury: 'First Century',
        navMillennium: 'Millennia',
        navFuture: 'Deep Future',
        mainTitle: 'Welcome to Earth, Population: Zero',
        mainSubtitle: 'What would happen to our planet if humanity suddenly vanished? This interactive timeline, based on the documentary "Life After People," explores the fate of our world—the decay of our cities, the resurgence of nature, and the legacy we leave behind. Scroll down or use the navigation to journey through time.',
        chartTitle: 'The Great Decay: Structural Integrity Over Time',
        chartSubtitle: 'This chart illustrates the estimated rate of decay for different types of human-made structures. As you scroll through the timeline, the chart will highlight the relevant period, showing how our creations succumb to the forces of nature without maintenance.',
        footerText: '© 2025, ShenYouX. An Exploration of a World Without Us. Inspired by "Life After People".',
        footerPrivacy: 'Privacy Policy',
        footerTerms: 'Terms of Use',
        chartYAxis: '% Structural Integrity',
        chartLabels: ['Start', '1 Year', '100 Years', '1k Years', '10k Years', '100k Years', '1M Years', '10M Years', '100M Years'],
        chartDatasetWood: 'Wooden Structures',
        chartDatasetSteel: 'Modern Steel/Concrete',
        chartDatasetStone: 'Massive Stone (Pyramids)',
        genTitle: 'See Your World Reclaimed',
        genSubtitle: 'Upload a picture of a familiar place—your street, a local park, or a favorite landmark. Our AI will envision how nature might reclaim it over the centuries.',
        genButton: 'Generate Future',
        genChooseImage: 'Choose an Image',
        genLoading: 'Generating...',
        genError: 'Could not generate images. Please try again.',
        genDisclaimer: 'Note: For clarity, these images focus on structural decay and nature\'s reclamation, omitting long-term geological and climatic changes.',
        genGoogleMap: 'Choose from Google Map',
        genConfirmSelection: 'Confirm Selection',
        genMapInstruction: 'Drag Pegman to explore Street View. Use the button below to confirm your location.',
        genTimeLabels: { one: '1 Year Later', hundred: '100 Years Later', thousand: '1,000 Years Later', tenThousand: '10,000 Years Later', hundredThousand: '100,000 Years Later', million: '1 Million Years Later' },
        genPrompts: { one: "The same location, 1 year after people. The first signs of neglect are visible. Weeds are cracking through pavement, paint is slightly peeling, and there's a layer of dust and grime on everything. Small animals and birds may be present, but nature has not yet fully taken over. The scene feels recently abandoned.", hundred: "The same location, 100 years after people. The structure is decaying, with crumbling concrete, rusting metal, and broken windows. Nature is taking over, with vines and trees growing on and around it. The atmosphere is quiet and abandoned.", thousand: "The same location, 1,000 years after people. The original structure is now a ruin, almost completely consumed by a mature forest. Only foundational shapes or the largest stone remnants are visible under thick moss and soil.", tenThousand: "The same location, 10,000 years after people. All visible traces of the structure are gone, buried under layers of earth. The landscape appears completely natural and wild, as if a building was never here. The terrain might have some unnatural, smooth hills where ruins lie buried.", hundredThousand: "The same location, 100,000 years after people. Any remnant of the structure is now a geological feature, perhaps a strangely shaped hill covered in a climax forest or grassland. The landscape is completely wild and may have been reshaped by glaciation or other major geological events.", million: "The same location, 1 million years after people. The landscape is utterly transformed by erosion and geological change. The ground where the structure stood is now part of a natural valley, hillside, or plain. The only hint of a human past would be a subtle, anomalous geological layer deep underground." },
        timelineData: { year: { id: 'year', title: 'The First Year: The World We Left Behind', intro: 'In the immediate aftermath of our disappearance, the systems that run our world begin to fail catastrophically. The initial changes are swift and dramatic as automated processes break down and nature begins its relentless reclamation.', events: [{ time: '24-48 Hours', description: 'Most power plants shut down due to lack of fuel, triggering a global blackout. Only those powered by hydro or wind continue for a short time. Subways begin to flood without pumps.' }, { time: '1 Week', description: 'Emergency generators at nuclear power plants run out of fuel. Without cooling, reactor cores melt down, leading to widespread radioactive contamination, though less severe than Chernobyl due to modern safety features.' }, { time: '2-3 Weeks', description: 'Domesticated animals, trapped in homes or farms, either escape or perish. Smaller dog breeds are preyed upon by larger, more feral dogs, wolves, and coyotes. Pet birds and exotic animals escape into new environments.' }, { time: '6 Months', description: 'Urban wildlife flourishes. Rats and cockroaches, deprived of human heat and waste, see their populations crash in colder climates. Weeds and invasive plants begin cracking pavement and foundations.' }, { time: '1 Year', description: 'Satellites begin to de-orbit and fall back to Earth. Vegetation growth is significant in cities, and roads in wetter climates are becoming difficult to distinguish.' }] }, century: { id: 'century', title: 'The First Century: Nature\'s Assault', intro: 'As decades pass, the forces of water, ice, and vegetation wage a full-scale war on our cities. Steel rusts, concrete cracks, and what once seemed permanent begins to crumble, while new ecosystems rise from our ruins.', events: [{ time: '20-25 Years', description: 'The Hoover Dam may remain functional, but many earthen dams have failed, altering landscapes. Steel structures like bridges and skyscrapers show serious signs of corrosion. Windows shatter from freeze-thaw cycles, allowing water and animals into buildings.' }, { time: '50 Years', description: 'Most wooden houses have collapsed. Asphalt roads are covered by soil and moss. Las Vegas is reclaimed by the desert, its iconic buildings collapsing. The Eiffel Tower\'s base is severely rusted.' }, { time: '75 Years', description: 'Most of the 600 million cars on Earth have rusted into unrecognizable shells. Tires have decomposed, leaving behind toxic chemical traces.' }, { time: '100 Years', description: 'Iconic steel bridges like the Golden Gate and Brooklyn Bridge collapse from cable corrosion. Skyscrapers, weakened by water damage and rust, begin to topple. Global warming effects slowly start to reverse as CO2 is reabsorbed by the expanding biosphere.' }] }, millennium: { id: 'millennium', title: 'The First Millennium: Erasing the Scars', intro: 'After centuries of decay, the very footprint of our civilization starts to fade. Forests cover our sprawling suburbs, and the world begins to resemble its pre-human state, though our legacy is still buried just beneath the surface.', events: [{ time: '200 Years', description: 'Major suspension bridges have all fallen. The Statue of Liberty\'s copper skin has corroded, and its steel skeleton gives way, causing it to collapse.' }, { time: '500 Years', description: 'Modern cities are nearly unrecognizable, covered by mature forests. Concrete structures and highway overpasses have have been pulverized by relentless freeze-thaw cycles and plant roots.' }, { time: '1,000 Years', description: 'Most traces of our cities are gone, buried under soil and vegetation. Only massive stone structures, like the pyramids, medieval castles, and parts of the Great Wall of China, remain visible on the surface.' }] }, future: { id: 'future', title: 'The Deep Future: A New Earth', intro: 'In the vast expanse of geologic time, almost all evidence of human existence is erased. The planet heals, life evolves, and any future intelligent species would have to dig deep to find any proof that we were ever here.', events: [{ time: '10,000 Years', description: 'Mount Rushmore is still recognizable but has been significantly eroded. The faces are indistinct. This is one of the last visible monuments to humanity.' }, { time: '50,000 Years', description: 'Glaciers from a new ice age may grind away the last remnants of our northern cities. Plastic waste has broken down into microscopic particles, creating a new layer in the fossil record.' }, { time: '10 Million Years', description: 'The only remaining evidence of our existence is fossils, our plastic-infused rock layer, and perhaps the bronze statues that fell into anaerobic mud, preserving them from corrosion.' }, { time: '100+ Million Years', description: 'The Earth is completely healed. Atmospheric CO2 levels have long since stabilized. New, diverse life forms dominate the planet, with no knowledge of the short-lived, industrious species that once ruled it.' }] } },
        backToHome: 'Back to Timeline',
        privacyTitle: 'Privacy Policy',
        privacyContent: [
            { heading: 'Introduction', body: 'Welcome to Life After People. We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you use our web application. By using the service, you agree to the collection and use of information in accordance with this policy.' },
            { heading: 'Information We Collect', body: 'We collect the following types of information: User-Provided Images: When you upload an image or select a location from Google Maps Street View, we process this image to generate new content. We do not store your original or generated images on our servers after your session ends. The data is processed in-memory and discarded.' },
            { heading: 'How We Use Your Information', body: 'The images you provide are used solely for the purpose of fulfilling your request to generate "Life After People" style visuals. The image data is sent to a third-party generative AI service (Google Gemini API) for processing and is not used for any other purpose, such as model training or identification.' },
            { heading: 'Third-Party Services', body: 'Our service relies on third-party APIs to function: Google Gemini API: For generating images. Your uploaded images are sent to Google for processing. We encourage you to review Google\'s Privacy Policy. Google Maps API: For the "Choose from Google Map" feature. Your interaction with the map is subject to the Google Maps/Google Earth Additional Terms of Service and Google\'s Privacy Policy.' },
            { heading: 'Data Security', body: 'We take reasonable measures to protect your information. However, no electronic transmission or storage is 100% secure. We process images transiently and do not permanently store them, minimizing risk.' },
            { heading: 'Changes to This Privacy Policy', body: 'We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.' },
        ],
        termsTitle: 'Terms of Use',
        termsContent: [
            { heading: '1. Acceptance of Terms', body: 'By accessing and using the Life After People web application ("the Service"), you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use the Service.' },
            { heading: '2. Description of Service', body: 'The Service provides users with AI-generated images that visualize a world without humans, based on an image they provide. This service is provided for entertainment and educational purposes only.' },
            { heading: '3. User-Generated Content', body: 'You retain all ownership rights to the images you upload. By uploading an image, you grant us a temporary, non-exclusive, worldwide, royalty-free license to use, modify, and display the image solely for the purpose of providing the Service to you. This license terminates automatically when your session ends.' },
            { heading: '4. Prohibited Conduct', body: 'You agree not to upload any content that is illegal, pornographic, hateful, infringing on intellectual property rights, or otherwise objectionable. We reserve the right to terminate access for users who violate these terms.' },
            { heading: '5. Disclaimer of Warranties', body: 'The Service is provided "as is" and "as available" without any warranties of any kind, express or implied. We do not warrant that the service will be uninterrupted, timely, secure, or error-free, nor do we make any warranty as to the results that may be obtained from the use of the service.' },
            { heading: '6. Limitation of Liability', body: 'In no event shall the creators of Life After People be liable for any direct, indirect, incidental, special, consequential or exemplary damages resulting from the use or the inability to use the service.' },
        ],
        genVideoScriptTitle: 'Your Video Script',
        genVideoScriptLoading: 'Generating video script...',
        genVideoScriptCopy: 'Copy Script',
        genVideoScriptCopied: 'Copied!',
        genDownloadAll: 'Download All',
        genZipping: 'Zipping...',
    },
    zh: {
        headerTitle: '人类消失后的世界',
        navYear: '第一年',
        navCentury: '第一个世纪',
        navMillennium: '千年',
        navFuture: '遥远的未来',
        mainTitle: '欢迎来到地球，人口：零',
        mainSubtitle: '如果人类突然消失，我们的星球会发生什么？这个基于纪录片《人类消失后的世界》的互动时间线，探讨了我们世界的命运——我们城市的衰败，自然的复苏，以及我们留下的遗产。向下滚动或使用导航来穿越时空。',
        chartTitle: '巨大的衰败：结构完整性随时间的变化',
        chartSubtitle: '此图表说明了不同类型人造结构的估计衰变率。当您滚动时间线时，图表将突出显示相关时期，展示我们的创造物在没有维护的情况下如何屈服于自然的力量。',
        footerText: '© 2025, ShenYouX. 探索一个没有我们的世界。灵感来自《人类消失后的世界》。',
        footerPrivacy: '隐私政策',
        footerTerms: '使用条款',
        chartYAxis: '结构完整性百分比',
        chartLabels: ['开始', '1年', '100年', '1千年', '1万年', '10万年', '1百万年', '1千万年', '1亿年'],
        chartDatasetWood: '木结构',
        chartDatasetSteel: '现代钢铁/混凝土',
        chartDatasetStone: '巨石结构（金字塔）',
        genTitle: '看你的世界被收回',
        genSubtitle: '上传一张熟悉地方的照片——你的街道、当地公园或最喜欢的地标。我们的人工智能将构想几个世纪后自然如何收回它。',
        genButton: '生成未来',
        genChooseImage: '选择图片',
        genLoading: '生成中...',
        genError: '无法生成图像。请再试一次。',
        genDisclaimer: '注意：为清晰起见，这些图像侧重于结构腐朽和自然复垦，省略了长期的地质和气候变化。',
        genGoogleMap: '从谷歌地图选择',
        genConfirmSelection: '确认选择',
        genMapInstruction: '拖动小黄人探索街景。使用下面的按钮确认您的位置。',
        genTimeLabels: { one: '1年后', hundred: '100年后', thousand: '1000年后', tenThousand: '10000年后', hundredThousand: '10万年后', million: '100万年后' },
        genPrompts: { one: "同一地点，1年后。最初的疏忽迹象可见。杂草从人行道裂缝中长出，油漆轻微剥落，所有东西上都覆盖着一层灰尘和污垢。可能有小动物和鸟类出现，但自然尚未完全接管。场景感觉像是最近被遗弃的。", hundred: "同一地点，100年后。建筑正在腐朽，混凝土崩裂，金属生锈，窗户破碎。自然正在接管，藤蔓和树木在建筑上和周围生长。气氛安静而被遗弃。", thousand: "同一地点，1000年后。原始建筑现在已成废墟，几乎完全被成熟的森林吞噬。只有地基形状或最大的石头残骸在厚厚的苔藓和土壤下可见。", tenThousand: "同一地点，10000年后。所有可见的建筑痕迹都消失了，被埋在土层之下。景观看起来完全自然和野生，好像这里从未有过建筑。地形可能会有一些不自然的、平滑的山丘，那里埋藏着废墟。", hundredThousand: "同一地点，10万年后。建筑的任何残余现在都已成为地质特征，可能是一座形状奇特的山丘，被顶级森林或草原覆盖。景观完全是野生的，可能已被冰川作用或其他重大地质事件重塑。", million: "同一地点，100万年后。景观因侵蚀和地质变化而彻底改变。建筑所在的地面现在是自然山谷、山坡或平原的一部分。人类过去的唯一线索将是地下深处一个微妙、异常的地质层。" },
        timelineData: { year: { id: 'year', title: '第一年：我们留下的世界', intro: '在我们消失后的瞬间，维持我们世界运转的系统开始灾难性地失灵。由于自动化过程的崩溃和自然无情的复苏，最初的变化是迅速而剧烈的。', events: [{ time: '24-48小时', description: '大多数发电厂因燃料耗尽而关闭，引发全球性停电。只有水电或风力发电站能短暂维持。地铁因水泵停止工作而开始淹水。' }, { time: '1周', description: '核电站的应急发电机燃料耗尽。没有冷却，反应堆堆芯熔毁，导致广泛的放射性污染，但由于现代安全特性，其严重程度低于切尔诺贝利。' }, { time: '2-3周', description: '被困在家中或农场的家养动物要么逃脱，要么死亡。小型犬种被更大型、更野性的狗、狼和郊狼捕食。宠物鸟和外来动物逃逸到新的环境中。' }, { time: '6个月', description: '城市野生动物繁盛。老鼠和蟑螂因失去人类提供的热量和废物，在寒冷气候下种群数量锐减。杂草和入侵植物开始撑裂人行道和地基。' }, { time: '1年', description: '卫星开始脱离轨道并坠回地球。城市植被显著增长，潮湿气候区的道路变得难以辨认。' }] }, century: { id: 'century', title: '第一个世纪：自然的猛攻', intro: '几十年过去，水、冰和植被的力量对我们的城市发动了全面战争。钢铁生锈，混凝土开裂，曾经看似永恒的东西开始崩塌，而新的生态系统则在我们的废墟上崛起。', events: [{ time: '20-25年', description: '胡佛水坝可能仍在运作，但许多土坝已经失效，改变了地貌。像桥梁和摩天大楼这样的钢结构出现严重的腐蚀迹象。窗户因冻融循环而破碎，让水和动物进入建筑物。' }, { time: '50年', description: '大多数木制房屋已经倒塌。沥青路面被土壤和苔藓覆盖。拉斯维加斯被沙漠夺回，其标志性建筑倒塌。埃菲尔铁塔的基座严重生锈。' }, { time: '75年', description: '地球上6亿辆汽车中的大多数已经锈成无法辨认的外壳。轮胎已经分解，留下有毒的化学痕迹。' }, { time: '100年', description: '像金门大桥和布鲁克林大桥这样的标志性钢桥因缆索腐蚀而倒塌。摩天大楼因水损害和锈蚀而变弱，开始倒塌。随着生物圈扩张重新吸收二氧化碳，全球变暖效应开始缓慢逆转。' }] }, millennium: { id: 'millennium', title: '第一个千年：抹去伤痕', intro: '经过几个世纪的衰败，我们文明的印记开始褪色。森林覆盖了我们庞大的郊区，世界开始恢复其人类出现前的状态，尽管我们的遗产仍埋藏在地表之下。', events: [{ time: '200年', description: '所有主要的悬索桥都已倒塌。自由女神像的铜皮已经腐蚀，其钢骨架断裂，导致其倒塌。' }, { time: '500年', description: '现代城市几乎无法辨认，被成熟的森林覆盖。混凝土结构和高速公路立交桥被无情的冻融循环和植物根系粉碎。' }, { time: '1000年', description: '我们城市的大多数痕迹都消失了，被埋在土壤和植被之下。只有像金字塔、中世纪城堡和长城部分这样的大型石结构仍然在地表可见。' }] }, future: { id: 'future', title: '遥远的未来：新地球', intro: '在广阔的地质时间尺度上，几乎所有人类存在的证据都被抹去。地球自我修复，生命进化，任何未来的智慧物种都必须深入挖掘才能找到我们曾经存在的证据。', events: [{ time: '1万年', description: '拉什莫尔山仍然可辨认，但已被严重侵蚀，面部模糊不清。这是人类最后可见的纪念碑之一。' }, { time: '5万年', description: '新冰河时代的冰川可能会磨掉我们北方城市的最后残余。塑料垃圾已分解成微观颗粒，在化石记录中形成一个新层。' }, { time: '1000万年', description: '我们存在的唯一剩余证据是化石、我们注入塑料的岩层，以及可能掉入缺氧泥浆中从而免于腐蚀的青铜雕像。' }, { time: '1亿年以上', description: '地球完全恢复。大气中的二氧化碳水平早已稳定。新的、多样化的生命形式主宰着这个星球，对曾经统治它的那个短暂而勤劳的物种一无所知。' }] } },
        backToHome: '返回时间线',
        privacyTitle: '隐私政策',
        privacyContent: [
            { heading: '引言', body: '欢迎来到“人类消失后的世界”。我们致力于保护您的隐私。本隐私政策解释了当您使用我们的网络应用程序时，我们如何收集、使用和保护您的信息。使用本服务即表示您同意我们根据本政策收集和使用信息。' },
            { heading: '我们收集的信息', body: '我们收集以下类型的信息：用户提供的图片：当您上传图片或从谷歌地图街景中选择位置时，我们会处理此图片以生成新内容。在您的会话结束后，我们不会在服务器上存储您的原始图片或生成的图片。数据在内存中处理后即被丢弃。' },
            { heading: '我们如何使用您的信息', body: '您提供的图片仅用于满足您生成“人类消失后的世界”风格视觉效果的请求。图片数据会发送给第三方生成式人工智能服务（Google Gemini API）进行处理，不会用于任何其他目的，如模型训练或身份识别。' },
            { heading: '第三方服务', body: '我们的服务依赖第三方API来运作：Google Gemini API：用于生成图片。您上传的图片会发送给谷歌进行处理。我们建议您查阅谷歌的隐私政策。Google Maps API：用于“从谷歌地图选择”功能。您与地图的互动受《谷歌地图/谷歌地球附加服务条款》和谷歌隐私政策的约束。' },
            { heading: '数据安全', body: '我们采取合理措施保护您的信息。但是，没有任何电子传输或存储是100%安全的。我们仅短暂处理图片，不进行永久存储，从而将风险降至最低。' },
            { heading: '本隐私政策的变更', body: '我们可能会不时更新我们的隐私政策。如有任何变更，我们会在此页面上发布新的隐私政策。建议您定期查看本隐私政策以了解任何变更。' },
        ],
        termsTitle: '使用条款',
        termsContent: [
            { heading: '1. 接受条款', body: '访问和使用“人类消失后的世界”网络应用程序（“本服务”），即表示您接受并同意遵守本协议的条款和规定。如果您不同意遵守这些条款，请勿使用本服务。' },
            { heading: '2. 服务说明', body: '本服务根据用户提供的图片，为用户提供AI生成的视觉效果，展示一个没有人类的世界。本服务仅供娱乐和教育目的。' },
            { heading: '3. 用户生成内容', body: '您保留您上传图片的所有权。上传图片即表示您授予我们一个临时的、非独家的、全球性的、免版税的许可，仅用于向您提供本服务而使用、修改和展示该图片。此许可在您的会话结束时自动终止。' },
            { heading: '4. 禁止行为', body: '您同意不上传任何非法、色情、仇恨、侵犯知识产权或其他令人反感的内容。我们保留终止违反这些条款的用户访问权限的权利。' },
            { heading: '5. 免责声明', body: '本服务按“原样”和“现有”基础提供，不附带任何明示或暗示的保证。我们不保证服务不会中断、及时、安全或无错误，也不对使用服务可能获得的结果作任何保证。' },
            { heading: '6. 责任限制', body: '在任何情况下，“人类消失后的世界”的创建者均不对因使用或无法使用本服务而导致的任何直接、间接、偶然、特殊、后果性或惩戒性损害负责。' },
        ],
        genVideoScriptTitle: '您的视频脚本',
        genVideoScriptLoading: '正在生成视频脚本...',
        genVideoScriptCopy: '复制脚本',
        genVideoScriptCopied: '已复制！',
        genDownloadAll: '下载全部',
        genZipping: '压缩中...',
    },
    ja: {
        headerTitle: '人類滅亡後の世界',
        navYear: '最初の年',
        navCentury: '最初の世紀',
        navMillennium: '千年紀',
        navFuture: '遠い未来',
        mainTitle: '地球へようこそ、人口：ゼロ',
        mainSubtitle: 'もし人類が突然姿を消したら、私たちの惑星はどうなるでしょうか？ドキュメンタリー「Life After People」に基づくこのインタラクティブなタイムラインは、私たちの世界の運命—都市の崩壊、自然の復活、そして私たちが残す遺産—を探ります。下にスクロールするか、ナビゲーションを使って時間を旅してください。',
        chartTitle: '大いなる崩壊：時間経過に伴う構造的完全性',
        chartSubtitle: 'このグラフは、さまざまな種類の人造構造物の推定崩壊率を示しています。タイムラインをスクロールすると、グラフが関連する期間をハイライトし、私たちの創造物がメンテナンスなしで自然の力にどのように屈していくかを示します。',
        footerText: '© 2025, ShenYouX. 私たちのいない世界の探求。「Life After People」に着想を得て。',
        footerPrivacy: 'プライバシーポリシー',
        footerTerms: '利用規約',
        chartYAxis: '構造的完全性（%）',
        chartLabels: ['開始', '1年後', '100年後', '1千年後', '1万年後', '10万年後', '100万年後', '1000万年後', '1億年後'],
        chartDatasetWood: '木造構造物',
        chartDatasetSteel: '現代の鋼鉄/コンクリート',
        chartDatasetStone: '巨大石造物（ピラミッド）',
        genTitle: 'あなたの世界が再生されるのを見る',
        genSubtitle: '身近な場所の写真—あなたの通り、地元の公園、またはお気に入りのランドマーク—をアップロードしてください。私たちのAIが、何世紀にもわたって自然がそれを取り戻す様子を想像します。',
        genButton: '未来を生成',
        genChooseImage: '画像を選択',
        genLoading: '生成中...',
        genError: '画像を生成できませんでした。もう一度お試しください。',
        genDisclaimer: '注：わかりやすくするため、これらの画像は構造物の崩壊と自然の再生に焦点を当てており、長期的な地質学的および気候的変動は省略しています。',
        genGoogleMap: 'Googleマップから選択',
        genConfirmSelection: '選択を確定',
        genMapInstruction: 'ペグマンをドラッグしてストリートビューを探索します。下のボタンで場所を確定してください。',
        genTimeLabels: { one: '1年後', hundred: '100年後', thousand: '1000年後', tenThousand: '10000年後', hundredThousand: '10万年後', million: '100万年後' },
        genPrompts: { one: "同じ場所、1年後。最初の放置の兆候が見られます。雑草が舗装を突き破り、塗装がわずかに剥がれ、すべてが埃と汚れの層で覆われています。小動物や鳥がいるかもしれませんが、自然はまだ完全には支配していません。最近放棄されたような雰囲気です。", hundred: "同じ場所、100年後。建物は崩壊し、コンクリートは崩れ、金属は錆び、窓は割れています。自然が支配し、ツタや木々が建物の上や周りに生えています。雰囲気は静かで放棄されています。", thousand: "同じ場所、1000年後。元の建物は今や廃墟となり、成熟した森にほぼ完全に飲み込まれています。厚い苔と土の下には、基礎の形や最大の石の残骸だけが見えます。", tenThousand: "同じ場所、10000年後。建物の目に見える痕跡はすべて消え、土の層の下に埋もれています。景観は完全に自然で野生的で、まるでここに建物がなかったかのようです。地形には、廃墟が埋まっている場所に不自然で滑らかな丘があるかもしれません。", hundredThousand: "同じ場所、10万年後。建物の残骸は今や地質学的特徴となっており、おそらくは極相林や草原に覆われた奇妙な形の丘でしょう。景観は完全に野生で、氷河作用やその他の主要な地質学的出来事によって再形成された可能性があります。", million: "同じ場所、100万年後。景観は侵食と地質学的変化によって完全に変貌しています。建物が立っていた地面は、今や自然の谷、丘の中腹、または平原の一部です。人間の過去の唯一の手がかりは、地下深くにある微妙で異常な地質層でしょう。" },
        timelineData: { year: { id: 'year', title: '最初の年：私たちが残した世界', intro: '私たちが姿を消した直後、私たちの世界を動かしていたシステムは壊滅的に機能不全に陥ります。自動化されたプロセスが停止し、自然が容赦ない回復を始めるため、初期の変化は迅速かつ劇的です。', events: [{ time: '24～48時間', description: 'ほとんどの発電所が燃料不足で停止し、世界的な停電を引き起こします。水力または風力で稼働するものだけが短時間稼働し続けます。地下鉄はポンプが停止するため浸水し始めます。' }, { time: '1週間', description: '原子力発電所の非常用発電機が燃料切れになります。冷却なしでは、原子炉の炉心がメルトダウンし、広範囲の放射能汚染を引き起こしますが、現代の安全機能のためチェルノブイリほど深刻ではありません。' }, { time: '2～3週間', description: '家や農場に閉じ込められた家畜は、逃げ出すか死に絶えます。小型犬種は、より大きく野生化した犬、オオカミ、コヨーテに捕食されます。ペットの鳥や外来動物は新しい環境に逃げ込みます。' }, { time: '6ヶ月', description: '都市の野生生物が繁栄します。人間が供給する熱とゴミを奪われたネズミやゴキブリは、寒冷な気候で個体数が激減します。雑草や侵入植物が舗装や基礎を割り始めます。' }, { time: '1年', description: '人工衛星が軌道を外れ、地球に落下し始めます。都市では植生が著しく成長し、湿潤な気候の道路は見分けがつきにくくなります。' }] }, century: { id: 'century', title: '最初の世紀：自然の猛攻撃', intro: '数十年が経過すると、水、氷、植生の力が私たちの都市に対して全面戦争を仕掛けます。鋼は錆び、コンクリートはひび割れ、かつて永続的に見えたものも崩れ始め、私たちの遺跡から新しい生態系が生まれます。', events: [{ time: '20～25年', description: 'フーバーダムは機能し続けるかもしれませんが、多くの土堰堤は決壊し、景観を変えます。橋や超高層ビルなどの鋼構造物には深刻な腐食の兆候が現れます。窓は凍結融解サイクルで割れ、建物内に水や動物が侵入します。' }, { time: '50年', description: 'ほとんどの木造家屋は倒壊しています。アスファルト道路は土と苔で覆われます。ラスベガスは砂漠に奪われ、象徴的な建物は崩壊します。エフェル塔の土台はひどく錆びています。' }, { time: '75年', description: '地球上にある6億台の自動車のほとんどは、見分けがつかないほどの残骸に錆びています。タイヤは分解され、有毒な化学物質の痕跡を残します。' }, { time: '100年', description: 'ゴールデンゲートブリッジやブルックリンブリッジのような象徴的な鋼橋は、ケーブルの腐食により崩壊します。水害と錆で弱体化した超高層ビルは倒れ始めます。拡大する生物圏がCO2を再吸収するにつれて、地球温暖化の影響はゆっくりと逆転し始めます。' }] }, millennium: { id: 'millennium', title: '最初の千年紀：傷跡を消す', intro: '数世紀の崩壊の後、私たちの文明の足跡そのものが薄れ始めます。広大な郊外を森が覆い、世界は人間以前の状態に似てきますが、私たちの遺産はまだ地表のすぐ下に埋もれています。', events: [{ time: '200年', description: '主要な吊り橋はすべて崩落しています。自由の女神像の銅の外皮は腐食し、鋼の骨格が崩れて倒壊します。' }, { time: '500年', description: '現代の都市はほとんど見分けがつかなくなり、成熟した森に覆われます。コンクリート構造物や高速道路の立体交差は、容赦ない凍結融解サイクルと植物の根によって粉砕されます。' }, { time: '1000年', description: '私たちの都市のほとんどの痕跡は消え、土と植生の下に埋もれます。ピラミッド、中世の城、万里の長城の一部のような巨大な石造物だけが地表に見えるままです。' }] }, future: { id: 'future', title: '遠い未来：新しい地球', intro: '広大な地質学的時間の中で、人類の存在の証拠はほとんどすべて消し去られます。地球は癒え、生命は進化し、将来の知的種は、私たちがかつてここにいたという証拠を見つけるために深く掘り下げなければならないでしょう。', events: [{ time: '1万年', description: 'ラシュモア山はまだ認識できますが、著しく侵食され、顔は不鮮明になっています。これは人類への最後の目に見える記念碑の一つです。' }, { time: '5万年', description: '新しい氷河期の氷河が、私たちの北部の都市の最後の名残を削り取るかもしれません。プラスチック廃棄物は微細な粒子に分解され、化石記録に新しい層を形成します。' }, { time: '1000万年', description: '私たちの存在の唯一の残された証拠は、化石、プラスチックが混入した岩石層、そしておそらく嫌気性の泥に落ちて腐食を免れた青銅像です。' }, { time: '1億年以上', description: '地球は完全に癒されます。大気中のCO2レベルはとうに安定しています。新しく多様な生命体が惑星を支配し、かつてそれを支配した短命で勤勉な種については何も知りません。' }] } },
        backToHome: 'タイムラインに戻る',
        privacyTitle: 'プライバシーポリシー',
        privacyContent: [
            { heading: 'はじめに', body: '「人類滅亡後の世界」へようこそ。私たちはあなたのプライバシー保護に取り組んでいます。本プライバシーポリシーは、お客様が当社のウェブアプリケーションをご利用になる際に、当社がお客様の情報をどのように収集、使用、保護するかを説明するものです。本サービスを利用することにより、お客様はこのポリシーに従って情報が収集・使用されることに同意したものとします。' },
            { heading: '収集する情報', body: '当社は以下の種類の情報を収集します：ユーザー提供の画像：お客様が画像をアップロードするか、Googleマップのストリートビューから場所を選択すると、当社はこの画像を処理して新しいコンテンツを生成します。セッション終了後、お客様のオリジナル画像または生成された画像はサーバーに保存されません。データはメモリ内で処理され、破棄されます。' },
            { heading: '情報の使用方法', body: 'ご提供いただいた画像は、「人類滅亡後の世界」風のビジュアルを生成するというお客様のご要望に応える目的でのみ使用されます。画像データは処理のために第三者の生成AIサービス（Google Gemini API）に送信され、モデルのトレーニングや個人特定など、その他の目的には使用されません。' },
            { heading: '第三者サービス', body: '当社のサービスは、機能するために第三者のAPIに依存しています：Google Gemini API：画像生成用。アップロードされた画像は処理のためにGoogleに送信されます。Googleのプライバシーポリシーをご確認いただくことをお勧めします。Google Maps API：「Googleマップから選択」機能用。マップとのやり取りは、Googleマップ/Google Earth追加利用規約およびGoogleのプライバシーポリシーの対象となります。' },
            { heading: 'データセキュリティ', body: '当社はお客様の情報を保護するために合理的な措置を講じます。しかし、電子的な送信や保存が100%安全であるとは限りません。当社は画像を一時的に処理し、恒久的に保存しないことでリスクを最小限に抑えています。' },
            { heading: '本プライバシーポリシーの変更', body: '当社はプライバシーポリシーを随時更新することがあります。変更があった場合は、このページに新しいプライバシーポリシーを掲載してお知らせします。定期的に本プライバシーポリシーを確認し、変更内容をご確認ください。' },
        ],
        termsTitle: '利用規約',
        termsContent: [
            { heading: '1. 規約への同意', body: '「人類滅亡後の世界」ウェブアプリケーション（以下「本サービス」）にアクセスし、利用することにより、お客様は本契約の条項に拘束されることに同意したものとみなされます。これらの条項に従うことに同意できない場合は、本サービスを利用しないでください。' },
            { heading: '2. サービスの説明', body: '本サービスは、ユーザーが提供した画像に基づき、人類のいない世界を視覚化するAI生成画像をユーザーに提供するものです。本サービスは、娯楽および教育目的でのみ提供されます。' },
            { heading: '3. ユーザー生成コンテンツ', body: 'アップロードした画像の所有権はすべてお客様に帰属します。画像をアップロードすることにより、お客様は、本サービスをお客様に提供する目的でのみ、当該画像を使用、変更、表示するための、一時的、非独占的、世界的、ロイヤリティフリーのライセンスを当社に付与するものとします。このライセンスは、お客様のセッションが終了すると自動的に終了します。' },
            { heading: '4. 禁止行為', body: '違法、ポルノ、憎悪的、知的財産権を侵害する、その他好ましくないコンテンツをアップロードしないことに同意するものとします。当社は、これらの規約に違反したユーザーのアクセスを終了させる権利を留保します。' },
            { heading: '5. 保証の否認', body: '本サービスは「現状有姿」および「提供可能な範囲」で提供され、明示または黙示を問わず、いかなる種類の保証もありません。当社は、サービスが中断されないこと、タイムリーであること、安全であること、エラーがないこと、また、サービスの利用から得られる結果について、いかなる保証も行いません。' },
            { heading: '6. 責任の制限', body: 'いかなる場合においても、「人類滅亡後の世界」の作成者は、本サービスの使用または使用不能に起因する直接的、間接的、付随的、特別、結果的または懲罰的な損害について一切責任を負わないものとします。' },
        ],
        genVideoScriptTitle: 'ビデオスクリプト',
        genVideoScriptLoading: 'ビデオスクリプトを生成中...',
        genVideoScriptCopy: 'スクリプトをコピー',
        genVideoScriptCopied: 'コピーしました！',
        genDownloadAll: 'すべてダウンロード',
        genZipping: '圧縮中...',
    }
};